### ISSUE TITLE
URDF compatibility build error on debian jessie

### ISSUE THREAD

**Issue by mryellow** [ros/robot_model#171]
Believe this might be an edge-case in `urdf_compatibility.h` which belongs here.

```
src/ros_controllers/diff_drive_controller/src/diff_drive_controller.cpp:61:36: error: ‘LinkConstSharedPtr’ in namespace ‘urdf’ does not name a type
 static bool isCylinder(const urdf::LinkConstSharedPtr& link)
```

`liburdfdom-dev` with Jessie is `0.3.0-1+b1`.

**Comment by wjwwood** [comment]
What version of ROS are you using?

**Comment by mryellow** [comment]
Kinetic, source install built from a fresh desktop rosinstall generator.

Looks like all the involved packages are at their most recent state, with no new changes.

```
- tar:
    local-name: ros/ros
    uri: https://github.com/ros-gbp/ros-release/archive/release/kinetic/ros/1.13.4-0.tar.gz
    version: ros-release-release-kinetic-ros-1.13.4-0
```

```
- tar:
    local-name: robot_model/robot_model
    uri: https://github.com/ros-gbp/robot_model-release/archive/release/kinetic/robot_model/1.12.5-0.tar.gz
    version: robot_model-release-release-kinetic-robot_model-1.12.5-0
- tar:
    local-name: robot_model/urdf
    uri: https://github.com/ros-gbp/robot_model-release/archive/release/kinetic/urdf/1.12.5-0.tar.gz
    version: robot_model-release-release-kinetic-urdf-1.12.5-0
```

```
- git:
    local-name: ros_control
    uri: https://github.com/ros-controls/ros_control.git
    version: kinetic-devel
- git:
    local-name: ros_controllers
    uri: https://github.com/ros-controls/ros_controllers.git
    version: kinetic-devel
- git:
    local-name: realtime_tools
    uri: https://github.com/ros-controls/realtime_tools.git
    version: kinetic-devel
- git:
    local-name: control_toolbox
    uri: https://github.com/ros-controls/control_toolbox.git
    version: kinetic-devel
```

**Comment by wjwwood** [comment]
Sorry for the delay in responding.

What version of `liburdfdom-dev` (see https://github.com/ros/rosdistro/blob/90ef1ed07cf065b2e6d819abdcdeff4881d6e7ef/rosdep/base.yaml#L2773) do you have installed?

It builds on our farm: http://repositories.ros.org/status_page/ros_kinetic_dj.html?q=diff_drive_controller

So I guess it must be a configuration of your machine?

**Comment by mryellow** [comment]
`liburdfdom-dev` with Jessie is `0.3.0-1+b1`.

> So I guess it must be a configuration of your machine?

With it being a source install, entirely possible. Everything does appear to be up-to-date with deployed versions, but you never know might be something upstream which confuses the whole situation, a few packages interacting here.

Haven't had a look at this for a number of weeks, if it's not coming up in your builds then might be safe to ignore and I'll find the time to figure out what is special about my build.

**Comment by wjwwood** [comment]
I'm going to close this since I could not reproduce and @mryellow hasn't had time to follow up. Please comment here if this needs to be reopened.

**Comment by mryellow** [comment]
Sorry haven't had a chance to touch any of this stuff for awhile.

Cleared root workspace and re-run rosinstall generator `desktop_full` which updated `robot_model` from `1.12.5` to `1.12.6`. Along the way patched dependency issues in `image_pipeline`.

Added extra packages outside of `desktop_full` for `diff_drive_controller`.

```
- git:
    local-name: ros_control
    uri: https://github.com/ros-controls/ros_control.git
    version: kinetic-devel
- git:
    local-name: ros_controllers
    uri: https://github.com/ros-controls/ros_controllers.git
    version: kinetic-devel
- git:
    local-name: realtime_tools
    uri: https://github.com/ros-controls/realtime_tools.git
    version: kinetic-devel
- git:
    local-name: control_toolbox
    uri: https://github.com/ros-controls/control_toolbox.git
    version: kinetic-devel
```

Result:

```
src/ros_controllers/diff_drive_controller/src/diff_drive_controller.cpp:61:36: error: ‘LinkConstSharedPtr’ in namespace ‘urdf’ does not name a type
 static bool isCylinder(const urdf::LinkConstSharedPtr& link)
```

No idea... Think I'll try it on actual hardware with binary packages rather than dev machine.
